version: "3"

services:
  caddy:
    image: forestbriggs/micro-caddy-production:1.0.1
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    # placement:
    #   constraints:
    #     - node.hostname == node-1
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  front-end:
    image: forestbriggs/front-end:1.0.4
    deploy:
      mode: replicated
      replicas: 1
    environment:
      BROKER_URL: "http://broker.learnforest.online"

  broker-service:
    image: forestbriggs/broker-service:1.0.2
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    image: forestbriggs/listener-service:1.0.1
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    image: forestbriggs/authentication-service:1.0.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  logger-service:
    image: forestbriggs/logger-service:1.0.2
    deploy:
      mode: replicated
      replicas: 1

  mail-service:
    image: forestbriggs/mail-service:1.0.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "John Smith"
      FROM_ADDRESS: john.smith@example.com

  rabbitmq:
    image: "rabbitmq:3.9-alpine"
    deploy:
      mode: replicated
      replicas: 1
    # need volume for production

  mailhog:
    image: "jcalonso/mailhog:latest"
    ports:
      - "8025:8025"
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    image: "mongo:4.2.16-bionic"
    ports: # wouldn't do in production
      - "27017:27017"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == node-1
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == node-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

volumes:
  caddy_data:
    external: true
  caddy_config:
